"""add model deployments and inference audit fields

Revision ID: 01bcb6f81802
Revises: 6936f012d734
Create Date: 2026-06-24 23:14:07.149465

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01bcb6f81802"
down_revision: str | None = "6936f012d734"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_deployments",
        sa.Column(
            "module",
            postgresql.ENUM(
                "histopathology", "survival", name="prediction_module", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("bundle_path", sa.String(length=1024), nullable=False),
        sa.Column("bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("architecture", sa.String(length=50), nullable=False),
        sa.Column("dataset_name", sa.String(length=100), nullable=False),
        sa.Column("dataset_mode", sa.String(length=20), nullable=False),
        sa.Column("synthetic_only", sa.Boolean(), nullable=False),
        sa.Column("eligible_for_demo", sa.Boolean(), nullable=False),
        sa.Column("device", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("loading", "active", "inactive", "failed", name="model_deployment_status"),
            nullable=False,
        ),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warmup_completed", sa.Boolean(), nullable=False),
        sa.Column("warmup_duration_ms", sa.Integer(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_deployments_model_id"), "model_deployments", ["model_id"], unique=False
    )
    op.add_column("predictions", sa.Column("request_id", sa.String(length=64), nullable=True))
    op.add_column(
        "predictions", sa.Column("client_reference", sa.String(length=100), nullable=True)
    )
    op.add_column("predictions", sa.Column("input_sha256", sa.String(length=64), nullable=True))
    op.add_column(
        "predictions", sa.Column("input_filename_safe", sa.String(length=128), nullable=True)
    )
    op.add_column("predictions", sa.Column("input_mime_type", sa.String(length=50), nullable=True))
    op.add_column("predictions", sa.Column("input_format", sa.String(length=20), nullable=True))
    op.add_column("predictions", sa.Column("input_size_bytes", sa.Integer(), nullable=True))
    op.add_column("predictions", sa.Column("input_width", sa.Integer(), nullable=True))
    op.add_column("predictions", sa.Column("input_height", sa.Integer(), nullable=True))
    op.add_column("predictions", sa.Column("processed_width", sa.Integer(), nullable=True))
    op.add_column("predictions", sa.Column("processed_height", sa.Integer(), nullable=True))
    op.add_column("predictions", sa.Column("model_deployment_id", sa.Uuid(), nullable=True))
    op.add_column("predictions", sa.Column("model_id", sa.String(length=255), nullable=True))
    op.add_column(
        "predictions", sa.Column("model_bundle_sha256", sa.String(length=64), nullable=True)
    )
    op.add_column("predictions", sa.Column("raw_probability", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("calibrated_probability", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("predicted_class", sa.String(length=50), nullable=True))
    op.add_column("predictions", sa.Column("decision", sa.String(length=20), nullable=True))
    op.add_column("predictions", sa.Column("threshold", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("review_lower_bound", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("review_upper_bound", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("preprocessing_time_ms", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("calibration_time_ms", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("explanation_time_ms", sa.Float(), nullable=True))
    op.add_column("predictions", sa.Column("total_time_ms", sa.Float(), nullable=True))
    op.add_column(
        "predictions",
        sa.Column(
            "explanation_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "predictions", sa.Column("explanation_status", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "predictions", sa.Column("safe_error_message", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "predictions", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_predictions_input_sha256"), "predictions", ["input_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_predictions_model_deployment_id"),
        "predictions",
        ["model_deployment_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_predictions_model_deployment_id_model_deployments",
        "predictions",
        "model_deployments",
        ["model_deployment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_predictions_model_deployment_id_model_deployments", "predictions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_predictions_model_deployment_id"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_input_sha256"), table_name="predictions")
    op.drop_column("predictions", "completed_at")
    op.drop_column("predictions", "safe_error_message")
    op.drop_column("predictions", "explanation_status")
    op.drop_column("predictions", "explanation_requested")
    op.drop_column("predictions", "total_time_ms")
    op.drop_column("predictions", "explanation_time_ms")
    op.drop_column("predictions", "calibration_time_ms")
    op.drop_column("predictions", "preprocessing_time_ms")
    op.drop_column("predictions", "review_upper_bound")
    op.drop_column("predictions", "review_lower_bound")
    op.drop_column("predictions", "threshold")
    op.drop_column("predictions", "decision")
    op.drop_column("predictions", "predicted_class")
    op.drop_column("predictions", "calibrated_probability")
    op.drop_column("predictions", "raw_probability")
    op.drop_column("predictions", "model_bundle_sha256")
    op.drop_column("predictions", "model_id")
    op.drop_column("predictions", "model_deployment_id")
    op.drop_column("predictions", "processed_height")
    op.drop_column("predictions", "processed_width")
    op.drop_column("predictions", "input_height")
    op.drop_column("predictions", "input_width")
    op.drop_column("predictions", "input_size_bytes")
    op.drop_column("predictions", "input_format")
    op.drop_column("predictions", "input_mime_type")
    op.drop_column("predictions", "input_filename_safe")
    op.drop_column("predictions", "input_sha256")
    op.drop_column("predictions", "client_reference")
    op.drop_column("predictions", "request_id")
    op.drop_index(op.f("ix_model_deployments_model_id"), table_name="model_deployments")
    op.drop_table("model_deployments")
    # ### end Alembic commands ###

    # Native PostgreSQL ENUM types are not dropped automatically when the table that
    # referenced them is dropped. `prediction_module` is reused from the initial schema
    # migration and stays - only the enum introduced by this migration is cleaned up here.
    postgresql.ENUM(name="model_deployment_status").drop(op.get_bind(), checkfirst=True)
